version: '2'
services:
  mediawiki:
    # MediaWiki
    #### Access via http://host-ip:8888
    #image: synctree/mediawiki
    image: simplyintricate/mediawiki
    logging:
      driver: syslog
      options:
        tag: "mediawiki"
    restart: always
    environment:
      - MEDIAWIKI_DB_HOST=mariadb
      - MEDIAWIKI_DB_USER=mediawiki
      - MEDIAWIKI_DB_PASSWORD=mediawiki
      - MEDIAWIKI_DB_NAME=mediawiki
    ports:
      - "8888:80/tcp"
      - "8889:443/tcp"
    links:
      - mariadb
    volumes:
      - ./mediawiki/data/LocalSettings.php:/usr/share/nginx/html/LocalSettings.php:ro
      #- <path>:/usr/share/nginx/html/images:ro
      #- <path>:/tmp/extensions
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    logging:
      driver: syslog 
      options:
        tag: "mariadb"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mediawiki
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki
    volumes:
      - ./mariadb/data:/var/lib/mysql
